***Initial Data Exploration***

In [ ]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("C:/Users/USER/Desktop/DataScience/sample_data.csv")

In [5]:
df.head()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,91,56,39,29,20,38,63,73,29,84,...,8,60,73,78,12,15,87,73,26,7
1,42,93,34,24,95,29,32,49,29,36,...,36,36,1,43,70,46,85,77,87,60
2,4,91,12,38,21,85,96,77,25,47,...,31,90,68,15,25,72,98,61,52,58
3,88,76,52,33,67,20,2,93,58,22,...,26,44,35,51,95,83,59,85,8,93
4,74,20,69,39,76,38,27,85,13,7,...,57,14,14,46,63,3,16,96,24,73

In [6]:
df.tail()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
95,40,97,28,87,44,17,54,58,17,49,...,24,5,51,70,14,5,17,42,86,80
96,86,36,70,20,34,30,19,6,51,72,...,25,60,32,30,26,68,65,6,58,52
97,8,34,78,25,43,28,8,81,38,94,...,40,31,49,14,93,80,88,44,98,96
98,84,18,66,7,78,82,3,72,46,47,...,6,52,10,99,33,14,69,77,9,48
99,64,100,86,88,36,55,59,8,46,44,...,42,30,69,33,18,29,9,82,86,1

In [7]:
df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='str')

In [8]:
df.shape

(100, 26)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int64
 1   B       100 non-null    int64
 2   C       100 non-null    int64
 3   D       100 non-null    int64
 4   E       100 non-null    int64
 5   F       100 non-null    int64
 6   G       100 non-null    int64
 7   H       100 non-null    int64
 8   I       100 non-null    int64
 9   J       100 non-null    int64
 10  K       100 non-null    int64
 11  L       100 non-null    int64
 12  M       100 non-null    int64
 13  N       100 non-null    int64
 14  O       100 non-null    int64
 15  P       100 non-null    int64
 16  Q       100 non-null    int64
 17  R       100 non-null    int64
 18  S       100 non-null    int64
 19  T       100 non-null    int64
 20  U       100 non-null    int64
 21  V       100 non-null    int64
 22  W       100 non-null    int64
 23  X       100 non-null    int64
 24  Y       100 non-null    int64
 25  Z       100 non-null    int64
dtypes: int64(26)
memory usage: 20.4 KB

In [10]:
df.describe()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,51.540000,51.790000,52.860000,47.100000,51.450000,45.820000,50.120000,47.430000,51.740000,50.080000,...,48.280000,50.750000,51.950000,46.32000,50.760000,48.240000,54.05000,49.820000,53.990000,54.850000
std,28.151617,29.259996,28.971954,29.276633,28.879889,28.596595,31.406195,29.039943,28.882772,27.493132,...,27.535131,29.544479,27.822807,28.39401,27.900299,30.699298,30.55691,29.572161,30.035835,29.863114
min,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,...,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000
25%,30.750000,23.500000,25.000000,21.000000,27.500000,20.750000,22.500000,24.000000,27.750000,27.000000,...,26.000000,24.000000,29.000000,25.00000,26.750000,19.000000,22.75000,20.500000,27.000000,32.000000
50%,51.000000,54.000000,56.000000,45.500000,52.500000,41.500000,50.000000,40.000000,52.500000,52.000000,...,45.500000,50.500000,49.000000,43.50000,55.500000,47.500000,62.50000,50.000000,51.500000,56.500000
75%,76.000000,75.000000,78.250000,75.250000,76.250000,72.250000,79.250000,74.000000,76.750000,69.000000,...,71.250000,75.250000,74.250000,68.50000,74.000000,77.000000,81.75000,73.250000,86.000000,80.000000
max,100.000000,100.000000,100.000000,98.000000,99.000000,98.000000,100.000000,98.000000,100.000000,99.000000,...,100.000000,100.000000,99.000000,99.00000,98.000000,99.000000,100.00000,100.000000,100.000000,100.000000

In [11]:
df.dtypes

A    int64
B    int64
C    int64
D    int64
E    int64
F    int64
G    int64
H    int64
I    int64
J    int64
K    int64
L    int64
M    int64
N    int64
O    int64
P    int64
Q    int64
R    int64
S    int64
T    int64
U    int64
V    int64
W    int64
X    int64
Y    int64
Z    int64
dtype: object

In [12]:
df.sample(5)

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
80,76,11,5,59,26,17,10,5,27,3,...,67,96,23,4,57,43,33,15,20,66
94,43,19,6,94,87,45,20,14,54,69,...,45,50,65,20,46,4,63,85,14,68
93,22,87,1,8,22,2,1,12,87,50,...,38,92,87,14,77,19,94,75,88,2
71,90,98,84,20,33,38,98,86,38,7,...,97,55,69,88,61,95,61,66,51,22
77,12,30,19,19,1,4,93,80,2,7,...,24,8,34,77,23,83,45,9,17,9

In [13]:
df.index #gives the row index label

RangeIndex(start=0, stop=100, step=1)

In [ ]:
df.ndim #gives number of dimensions of dataframe

2

In [15]:
df.size

2600

**Missing Data Handling**

In [16]:
df.isnull()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df.isnull().sum()

A    0
B    0
C    0
D    0
E    0
F    0
G    0
H    0
I    0
J    0
K    0
L    0
M    0
N    0
O    0
P    0
Q    0
R    0
S    0
T    0
U    0
V    0
W    0
X    0
Y    0
Z    0
dtype: int64

In [18]:
df.dropna()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,91,56,39,29,20,38,63,73,29,84,...,8,60,73,78,12,15,87,73,26,7
1,42,93,34,24,95,29,32,49,29,36,...,36,36,1,43,70,46,85,77,87,60
2,4,91,12,38,21,85,96,77,25,47,...,31,90,68,15,25,72,98,61,52,58
3,88,76,52,33,67,20,2,93,58,22,...,26,44,35,51,95,83,59,85,8,93
4,74,20,69,39,76,38,27,85,13,7,...,57,14,14,46,63,3,16,96,24,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,40,97,28,87,44,17,54,58,17,49,...,24,5,51,70,14,5,17,42,86,80
96,86,36,70,20,34,30,19,6,51,72,...,25,60,32,30,26,68,65,6,58,52
97,8,34,78,25,43,28,8,81,38,94,...,40,31,49,14,93,80,88,44,98,96
98,84,18,66,7,78,82,3,72,46,47,...,6,52,10,99,33,14,69,77,9,48
99,64,100,86,88,36,55,59,8,46,44,...,42,30,69,33,18,29,9,82,86,1

In [19]:
df.notnull()

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
96,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
97,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
98,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
99,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [20]:
df.interpolate() #fills missing values using interpolation

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,91,56,39,29,20,38,63,73,29,84,...,8,60,73,78,12,15,87,73,26,7
1,42,93,34,24,95,29,32,49,29,36,...,36,36,1,43,70,46,85,77,87,60
2,4,91,12,38,21,85,96,77,25,47,...,31,90,68,15,25,72,98,61,52,58
3,88,76,52,33,67,20,2,93,58,22,...,26,44,35,51,95,83,59,85,8,93
4,74,20,69,39,76,38,27,85,13,7,...,57,14,14,46,63,3,16,96,24,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,40,97,28,87,44,17,54,58,17,49,...,24,5,51,70,14,5,17,42,86,80
96,86,36,70,20,34,30,19,6,51,72,...,25,60,32,30,26,68,65,6,58,52
97,8,34,78,25,43,28,8,81,38,94,...,40,31,49,14,93,80,88,44,98,96
98,84,18,66,7,78,82,3,72,46,47,...,6,52,10,99,33,14,69,77,9,48
99,64,100,86,88,36,55,59,8,46,44,...,42,30,69,33,18,29,9,82,86,1

**Selection and Filtering**

In [23]:
df["A"] # selects single column A as a series

0     91
1     42
2      4
3     88
4     74
      ..
95    40
96    86
97     8
98    84
99    64
Name: A, Length: 100, dtype: int64

In [24]:
df[["A","B"]]

     A    B
0   91   56
1   42   93
2    4   91
3   88   76
4   74   20
..  ..  ...
95  40   97
96  86   36
97   8   34
98  84   18
99  64  100

[100 rows x 2 columns]

In [27]:
df.loc[0:5,"A":"C"]

    A   B   C
0  91  56  39
1  42  93  34
2   4  91  12
3  88  76  52
4  74  20  69
5  88  97  17

In [28]:
df.iloc[0:5,0:3]

    A   B   C
0  91  56  39
1  42  93  34
2   4  91  12
3  88  76  52
4  74  20  69

In [31]:
df[df["A"]>90]

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,91,56,39,29,20,38,63,73,29,84,...,8,60,73,78,12,15,87,73,26,7
11,100,81,57,27,37,71,94,24,44,85,...,71,85,14,24,43,61,84,98,72,72
18,98,76,11,42,18,6,21,3,97,78,...,2,56,4,31,97,91,45,50,92,36
49,99,66,73,50,79,64,79,27,70,28,...,18,29,64,25,56,6,42,44,14,3
65,95,49,10,47,69,93,29,31,8,44,...,1,72,69,84,37,99,86,7,44,50
70,100,89,45,98,83,20,59,46,64,64,...,62,6,87,35,2,34,81,38,13,84
85,96,74,92,53,97,88,51,25,48,44,...,17,88,32,99,66,33,48,10,91,76

In [34]:
df.query("A> 90 and B < 100")

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
0,91,56,39,29,20,38,63,73,29,84,...,8,60,73,78,12,15,87,73,26,7
11,100,81,57,27,37,71,94,24,44,85,...,71,85,14,24,43,61,84,98,72,72
18,98,76,11,42,18,6,21,3,97,78,...,2,56,4,31,97,91,45,50,92,36
49,99,66,73,50,79,64,79,27,70,28,...,18,29,64,25,56,6,42,44,14,3
65,95,49,10,47,69,93,29,31,8,44,...,1,72,69,84,37,99,86,7,44,50
70,100,89,45,98,83,20,59,46,64,64,...,62,6,87,35,2,34,81,38,13,84
85,96,74,92,53,97,88,51,25,48,44,...,17,88,32,99,66,33,48,10,91,76

In [36]:
df.filter(items=["A","B"])

     A    B
0   91   56
1   42   93
2    4   91
3   88   76
4   74   20
..  ..  ...
95  40   97
96  86   36
97   8   34
98  84   18
99  64  100

[100 rows x 2 columns]

In [ ]:
df.at[0,"A"] #Access single value fast by label

np.int64(91)